// Source: https://docs.google.com/document/d/153t_EOB9nIp7ITDT98cDhKjezl3CQyTOivOpBcteyrQ/edit
// Revision: ANLCKQmzRm5EvKWGxNzndFpXbsr8hS5fZn2HkPRPL-rVXlUc5tOsrEXqIAf6GxwOFUDcFX0Gf5KvOHda8yjH6xi7ulMLRMcasajRWXRytUs
// Keep the wording and order aligned with the source document.
export interface AmlKycParagraph {
  text: string;
  style: "HEADING_1" | "HEADING_2" | "NORMAL_TEXT";
  list: boolean;
}

export const amlKycParagraphs: AmlKycParagraph[] = [
  { text: "2SETTLE AML/KYC POLICY", style: "HEADING_1", list: false },
  { text: "Effective Date: 15 September 2026", style: "NORMAL_TEXT", list: false },
  { text: "The 2Settle Ltd is committed to preventing its Services from being used for money laundering, terrorist financing, fraud, sanctions evasion or other unlawful activities.", style: "NORMAL_TEXT", list: false },
  { text: "This public policy provides a high-level description of 2Settle’s approach. It does not disclose confidential monitoring methodologies, risk thresholds or security controls.", style: "NORMAL_TEXT", list: false },
  { text: "1. Customer Identification", style: "HEADING_2", list: false },
  { text: "2Settle may require users to provide information necessary to establish and verify their identity.", style: "NORMAL_TEXT", list: false },
  { text: "Depending on the user and transaction, this may include:", style: "NORMAL_TEXT", list: false },
  { text: "legal name;", style: "NORMAL_TEXT", list: true },
  { text: "date of birth;", style: "NORMAL_TEXT", list: true },
  { text: "telephone number;", style: "NORMAL_TEXT", list: true },
  { text: "address;", style: "NORMAL_TEXT", list: true },
  { text: "identification information;", style: "NORMAL_TEXT", list: true },
  { text: "BVN or NIN information where applicable;", style: "NORMAL_TEXT", list: true },
  { text: "photograph or verification evidence; and", style: "NORMAL_TEXT", list: true },
  { text: "other reasonably required information.", style: "NORMAL_TEXT", list: true },
  { text: "2. Business Verification", style: "HEADING_2", list: false },
  { text: "Businesses may be required to provide:", style: "NORMAL_TEXT", list: false },
  { text: "registered business name;", style: "NORMAL_TEXT", list: true },
  { text: "registration information;", style: "NORMAL_TEXT", list: true },
  { text: "business address;", style: "NORMAL_TEXT", list: true },
  { text: "directors;", style: "NORMAL_TEXT", list: true },
  { text: "shareholders;", style: "NORMAL_TEXT", list: true },
  { text: "beneficial owners;", style: "NORMAL_TEXT", list: true },
  { text: "nature of business;", style: "NORMAL_TEXT", list: true },
  { text: "expected transaction activity; and", style: "NORMAL_TEXT", list: true },
  { text: "supporting documentation.", style: "NORMAL_TEXT", list: true },
  { text: "Additional information may be required depending on risk and transaction activity.", style: "NORMAL_TEXT", list: false },
  { text: "3. Transaction Monitoring", style: "HEADING_2", list: false },
  { text: "2Settle may monitor transactions for activity inconsistent with expected use, applicable law or our risk standards.", style: "NORMAL_TEXT", list: false },
  { text: "Transactions may be reviewed before, during or after processing.", style: "NORMAL_TEXT", list: false },
  { text: "2Settle may request explanations or supporting documentation where necessary.", style: "NORMAL_TEXT", list: false },
  { text: "4. Source of Funds", style: "HEADING_2", list: false },
  { text: "For certain transactions, users may be required to establish the legitimate source of the digital assets or funds involved.", style: "NORMAL_TEXT", list: false },
  { text: "Supporting information may include transaction records, business documents or other appropriate evidence.", style: "NORMAL_TEXT", list: false },
  { text: "Failure to provide satisfactory information may result in delay, restriction or rejection.", style: "NORMAL_TEXT", list: false },
  { text: "5. Sanctions and Restricted Activity", style: "HEADING_2", list: false },
  { text: "2Settle may screen users, businesses, transactions and counterparties against applicable sanctions and other relevant risk information.", style: "NORMAL_TEXT", list: false },
  { text: "We will not knowingly facilitate transactions prohibited under applicable law.", style: "NORMAL_TEXT", list: false },
  { text: "6. Enhanced Due Diligence", style: "HEADING_2", list: false },
  { text: "Higher-risk users, businesses or transactions may be subject to additional review.", style: "NORMAL_TEXT", list: false },
  { text: "The extent of such review is determined using internal risk procedures and will not necessarily be disclosed to users.", style: "NORMAL_TEXT", list: false },
  { text: "7. Suspicious Activity", style: "HEADING_2", list: false },
  { text: "Where 2Settle identifies activity reasonably suspected to involve fraud, money laundering, terrorist financing, sanctions violations or other unlawful conduct, we may restrict the relevant transaction or account and take actions required or permitted by law.", style: "NORMAL_TEXT", list: false },
  { text: "Where legally prohibited, we may not be able to inform the affected user of the reason for an investigation or action.", style: "NORMAL_TEXT", list: false },
  { text: "8. Record Keeping", style: "HEADING_2", list: false },
  { text: "2Settle may retain verification, transaction and compliance records for periods reasonably required by applicable law, risk management and legitimate business requirements.", style: "NORMAL_TEXT", list: false },
  { text: "9. Cooperation", style: "HEADING_2", list: false },
  { text: "Where legally required, 2Settle may cooperate with competent authorities and respond to lawful requests for information.", style: "NORMAL_TEXT", list: false },
  { text: "10. User Responsibility", style: "HEADING_2", list: false },
  { text: "Users must provide truthful information and must not use 2Settle to conceal the origin, ownership, purpose or destination of assets or funds.", style: "NORMAL_TEXT", list: false },
  { text: "Providing false or misleading information may result in restriction or termination of access.", style: "NORMAL_TEXT", list: false },
  { text: "11. Contact", style: "HEADING_2", list: false },
  { text: "Compliance-related enquiries may be directed to:", style: "NORMAL_TEXT", list: false },
  { text: "support@2settle.io", style: "NORMAL_TEXT", list: false },
];
