// Source: https://docs.google.com/document/d/11Oj3AxQaCRpcGtEs1I55TlV76x7NuBa9VRRM4XE-aYo/edit
// Revision: ANLCKQmAZvMrhWVQEI4EZo7nhC-srQnZJsEWyvKv9JNcO5fgxtM7lCxHfAYFHRSQGSpwCaYsTdjUbKzxPMY4CvGRjYsQ7pD8xAk2JQuaFLE
// The source's "Production implementation" notes are instructions, not public policy text.
export interface CryptoRefundParagraph {
  text: string;
  style: "HEADING_1" | "HEADING_2" | "NORMAL_TEXT";
  list: boolean;
}

export const cryptoRefundParagraphs: CryptoRefundParagraph[] = [
  { text: "CRYPTO TRANSACTION, CANCELLATION & REFUND POLICY", style: "HEADING_1", list: false },
  { text: "Effective Date: 15 September 2026", style: "NORMAL_TEXT", list: false },
  { text: "This Policy forms part of the Terms and Conditions governing use of 2Settle.", style: "NORMAL_TEXT", list: false },
  { text: "1. Blockchain Transactions", style: "HEADING_2", list: false },
  { text: "Digital-asset transfers recorded on a blockchain are generally irreversible.", style: "NORMAL_TEXT", list: false },
  { text: "Users must verify the asset, network, wallet address and amount before sending a transaction.", style: "NORMAL_TEXT", list: false },
  { text: "Once a blockchain transfer has been broadcast or confirmed, 2Settle cannot reverse the blockchain itself.", style: "NORMAL_TEXT", list: false },
  { text: "2. Quotes", style: "HEADING_2", list: false },
  { text: "Transaction quotes may have a limited validity period.", style: "NORMAL_TEXT", list: false },
  { text: "If the required digital asset is not received within the applicable quote period, the original quote may expire.", style: "NORMAL_TEXT", list: false },
  { text: "2Settle may then:", style: "NORMAL_TEXT", list: false },
  { text: "provide a new quote;", style: "NORMAL_TEXT", list: true },
  { text: "recalculate the settlement amount using the applicable rate; or", style: "NORMAL_TEXT", list: true },
  { text: "request further instructions where appropriate.", style: "NORMAL_TEXT", list: true },
  { text: "3. Incorrect Amounts", style: "HEADING_2", list: false },
  { text: "If you send less than the required amount, the transaction may be placed on hold until the discrepancy is resolved.", style: "NORMAL_TEXT", list: false },
  { text: "Depending on the circumstances, 2Settle may permit an additional transfer, recalculate the transaction or process a refund where possible.", style: "NORMAL_TEXT", list: false },
  { text: "If you send more than required, 2Settle will determine the appropriate resolution based on the transaction and operational circumstances.", style: "NORMAL_TEXT", list: false },
  { text: "Network and other applicable costs may be deducted where a return transaction is required.", style: "NORMAL_TEXT", list: false },
  { text: "4. Wrong Network or Unsupported Asset", style: "HEADING_2", list: false },
  { text: "Sending an asset through an unsupported network or sending an unsupported asset may result in permanent loss.", style: "NORMAL_TEXT", list: false },
  { text: "2Settle does not guarantee recovery.", style: "NORMAL_TEXT", list: false },
  { text: "Where recovery is technically possible, recovery may require additional time and may be subject to network, provider, administrative and recovery costs.", style: "NORMAL_TEXT", list: false },
  { text: "2Settle may decline recovery where attempting it would create disproportionate technical, security or compliance risk.", style: "NORMAL_TEXT", list: false },
  { text: "5. Cancellation", style: "HEADING_2", list: false },
  { text: "A transaction cannot ordinarily be cancelled after the digital asset has been transferred and processing has commenced.", style: "NORMAL_TEXT", list: false },
  { text: "Cancellation requests received before processing has materially commenced will be considered where technically and operationally possible.", style: "NORMAL_TEXT", list: false },
  { text: "Submitting a cancellation request does not guarantee cancellation.", style: "NORMAL_TEXT", list: false },
  { text: "6. Failed Settlement", style: "HEADING_2", list: false },
  { text: "Where 2Settle has received the required digital asset but the intended recipient settlement fails, 2Settle will take reasonable steps to investigate.", style: "NORMAL_TEXT", list: false },
  { text: "Depending on the circumstances, we may:", style: "NORMAL_TEXT", list: false },
  { text: "retry the settlement;", style: "NORMAL_TEXT", list: true },
  { text: "request corrected recipient information;", style: "NORMAL_TEXT", list: true },
  { text: "use an alternative available settlement route;", style: "NORMAL_TEXT", list: true },
  { text: "place the transaction under review; or", style: "NORMAL_TEXT", list: true },
  { text: "arrange an appropriate refund where settlement cannot reasonably be completed.", style: "NORMAL_TEXT", list: true },
  { text: "Users should not initiate duplicate transactions while an existing transaction remains under investigation unless instructed to do so.", style: "NORMAL_TEXT", list: false },
  { text: "7. Refund Value", style: "HEADING_2", list: false },
  { text: "Where a refund is approved, the refund may not equal the original fiat value quoted for the transaction.", style: "NORMAL_TEXT", list: false },
  { text: "The amount returned may reflect:", style: "NORMAL_TEXT", list: false },
  { text: "the digital asset involved;", style: "NORMAL_TEXT", list: true },
  { text: "applicable market movements;", style: "NORMAL_TEXT", list: true },
  { text: "blockchain/network fees;", style: "NORMAL_TEXT", list: true },
  { text: "conversion already undertaken;", style: "NORMAL_TEXT", list: true },
  { text: "third-party charges; and", style: "NORMAL_TEXT", list: true },
  { text: "reasonable recovery or processing costs.", style: "NORMAL_TEXT", list: true },
  { text: "The applicable resolution will depend on the stage reached by the original transaction.", style: "NORMAL_TEXT", list: false },
  { text: "8. Compliance Holds", style: "HEADING_2", list: false },
  { text: "A transaction or refund may be delayed where additional identity, transaction or source-of-funds information is required.", style: "NORMAL_TEXT", list: false },
  { text: "2Settle will not process a refund or settlement where doing so would violate applicable law or a binding legal restriction.", style: "NORMAL_TEXT", list: false },
  { text: "9. Bank or Recipient Errors", style: "HEADING_2", list: false },
  { text: "Users are responsible for verifying recipient details before confirming a transaction.", style: "NORMAL_TEXT", list: false },
  { text: "If settlement has already been completed to the account specified by the user, recovery may depend on the recipient institution or Settlement Provider and cannot be guaranteed.", style: "NORMAL_TEXT", list: false },
  { text: "2Settle will take reasonable steps to assist where practicable.", style: "NORMAL_TEXT", list: false },
  { text: "10. How to Raise a Transaction Dispute", style: "HEADING_2", list: false },
  { text: "Send transaction disputes to:", style: "NORMAL_TEXT", list: false },
  { text: "support@2settle.io", style: "NORMAL_TEXT", list: false },
  { text: "Include, where applicable:", style: "NORMAL_TEXT", list: false },
  { text: "your name;", style: "NORMAL_TEXT", list: true },
  { text: "2Settle transaction reference;", style: "NORMAL_TEXT", list: true },
  { text: "transaction hash;", style: "NORMAL_TEXT", list: true },
  { text: "amount;", style: "NORMAL_TEXT", list: true },
  { text: "asset/network;", style: "NORMAL_TEXT", list: true },
  { text: "recipient information; and", style: "NORMAL_TEXT", list: true },
  { text: "a description of the issue.", style: "NORMAL_TEXT", list: true },
  { text: "Never send private keys, seed phrases or wallet recovery phrases to 2Settle support.", style: "NORMAL_TEXT", list: false },
  { text: "11. Final Provision", style: "HEADING_2", list: false },
  { text: "This Policy should be read together with the 2Settle Terms & Conditions and 2Settle Privacy Policy.", style: "NORMAL_TEXT", list: false },
  { text: "Where there is a conflict, the Terms & Conditions shall govern unless applicable law requires otherwise.", style: "NORMAL_TEXT", list: false },
];
